### ISSUE TITLE
Pretty logging

### ISSUE THREAD

**Issue by balcieren** [hertz-contrib/logger#14]
How can I active this feature ?

```go
log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})
```

**Comment by li-jin-gou** [comment]
Do I think it is possible to use `hertzZerolog.WithOutput` or  `SetOutput`? 

refer to 
- https://github.com/hertz-contrib/logger/blob/main/zerolog/logger.go#L69
- https://github.com/hertz-contrib/logger/blob/main/zerolog/options.go#L49

**Comment by balcieren** [comment]
this works

```go
	hlog.SetLogger(hertzZerolog.New(
		hertzZerolog.WithOutput(zerolog.ConsoleWriter{Out: os.Stderr}),
	))
```
