### ISSUE TITLE
Support zerolog.MultiLevelWriter

### ISSUE THREAD

**Issue by yuyuko233** [hertz-contrib/logger#17]
**Is your feature request related to a problem? Please describe.**

能否支持[zerolog.MultiLevelWriter](https://github.com/rs/zerolog#multiple-log-output)?
Is it possible to support [zerolog.MultiLevelWriter](https://github.com/rs/zerolog#multiple-log-output)?

**Describe the solution you'd like**

支持[zerolog.MultiLevelWriter](https://github.com/rs/zerolog#multiple-log-output)
Support [zerolog.MultiLevelWriter](https://github.com/rs/zerolog#multiple-log-output).

```golang
consoleWriter := hertzZerolog.ConsoleWriter{Out: os.Stdout}

logger := hertzZerolog.New(
    hertzZerolog.MultiLevelWriter(consoleWriter, os.Stdout),
)
```

**Comment by li-jin-gou** [comment]
Of course and PR are welcome.
