### ISSUE TITLE
accesslog will panic when first time interval not reached

### ISSUE THREAD

**Issue by beihaifeiwu** [hertz-contrib/logger#30]
**Describe the bug**

accesslog will panic when first time interval not reached

**Expected behavior**

no panic

**Screenshots**
![image](https://user-images.githubusercontent.com/5372382/234857748-4ff863b2-bee3-4b8f-b15c-102f5f2664f2.png)

**Comment by welkeyever** [comment]
Is the screenshot associated to this repo? If so, adding the link to the original code would help🙏
