### ISSUE TITLE
how to use zap.field? 

### ISSUE THREAD

**Issue by wuyunhua1987** [hertz-contrib/logger#32]
eg: zap.String("name", "john"), zap.Int("age", 18), then json output likes this: {"name": "john", "age": 18}

**Comment by li-jin-gou** [comment]
Not supported, complex log printing is recommended using the native zap

**Comment by li-jin-gou** [comment]
However, it is recommended that hlog be injected into the zap implementation as well to ensure that both framework logs and business logs can be seen.

**Comment by wuyunhua1987** [comment]
what about `logger.Infow`? this is what i need but it hasn't been implemented

**Comment by li-jin-gou** [comment]
> what about `logger.Infow`? this is what i need but it hasn't been implemented

not support and i recommend using zap directly, you can use hlog.SetLogger to inject zap and ensure that the framework logs are collected by you as well.

**Comment by Skyenought** [comment]
@wuyunhua1987 现在 zap 支持导出原生 logger, 以支持复杂操作

```go
logger := hertzap.NewLogger()
hlog.SetLogger(logger)

h.GET("/hello", func(ctx context.Context, c *app.RequestContext) {
	logger.Logger().Info("Hello, World!", zap.Int("status", c.Response().StatusCode()))
	c.String(consts.StatusOK, "Hello hertz!")
})
```
