### ISSUE TITLE
[bug] 使用hertzZerolog不能正确获取caller

### ISSUE THREAD

**Issue by wsrer** [hertz-contrib/logger#34]
**Describe the bug**

使用hertzZerolog不能正确获取caller

**To Reproduce**

```go
package main

import "os"
import (
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzZerolog "github.com/hertz-contrib/logger/zerolog"
)

func main() {
	hlog.SetLogger(hertzZerolog.New(
		hertzZerolog.WithOutput(os.Stdout),      // allows to specify output
		hertzZerolog.WithLevel(hlog.LevelDebug), // option with log level
		hertzZerolog.WithTimestamp(),            // option with timestamp
		hertzZerolog.WithCaller(),
	))
	hlog.Info("ok")
}

```

**Expected behavior**

日志的caller应为`main.main`

**Screenshots**

![image](https://github.com/hertz-contrib/logger/assets/69560752/e92151b6-81e1-49f2-b44b-b949ace33af8)

**Comment by li-jin-gou** [comment]
hlog 会 warp 一层 zerolog ，导致计算 caller 文件行数的结果错了。

**Comment by li-jin-gou** [comment]
zap 也有同样的问题，caller 不对的话可以参考  https://github.com/uber-go/zap/issues/715#issuecomment-493124091 设置 option
