### ISSUE TITLE
zerolog CtxInfo 在调用时并没有把 ctx 传入 logger

### ISSUE THREAD

**Issue by liuzhaowei55** [hertz-contrib/logger#38]
这样会造成 zerolog hook 获取 ctx 为 nil

https://github.com/hertz-contrib/logger/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by li-jin-gou** [comment]
@liuzhaowei55 你愿意提交一个 pr 修复它嘛🌹?，如果不的话我会暂时先将它放到todo或新手任务中。
