### ISSUE TITLE
zap ctxLogs Extrakey nil

### ISSUE THREAD

**Issue by xinjiyuan97** [hertz-contrib/logger#39]
**Describe the bug**

在调用CtxDebugf的时候发现无法抽取Context中的RequestID，debug后发现是ctx.Value(ExtraKey)无法返回正确值，需要转化为ctx.Value(string(Extrakey))或者提供指定ExtraKey类型的能力才可以
**To Reproduce**

**Expected behavior**

**Screenshots**
![img_v2_280d3626-651b-42be-96c6-1bb9dec53a9g](https://github.com/hertz-contrib/logger/assets/12007836/3e91de31-96b0-4aff-b43b-42acbaf9fe0a)

**Hertz version:**

Please provide the version of Hertz you are using.

**Environment:**

The output of `go env`.

**Additional context**

**Comment by Skyenought** [comment]
@xinjiyuan97 实际你使用的时候应该是转为 ExtraKey 类型

```go
func main() {
	logger := hzap.NewLogger(
		hzap.WithExtraKeys([]hzap.ExtraKey{
			"test",
		}),
	)
	hlog.SetLogger(logger)
	h := server.New()
	h.GET("/", func(c context.Context, ctx *app.RequestContext) {
		context.WithValue(c, hzap.ExtraKey("test"), "test")
	})
}

**Comment by xinjiyuan97** [comment]
实际部分key通过第三方中间件生成，并不能保证所有key的类型都是ExtraKey

**Comment by li-jin-gou** [comment]
这个地方有可能直接用 string 嘛，我看 extrakey 的类型目前其实也是 string。

**Comment by rogerogers** [comment]
https://pkg.go.dev/context#WithValue
withvalue不建议用内置类型，所以我的理解是context里一般不会有string定义的内容吧。

**Comment by xinjiyuan97** [comment]
> https://pkg.go.dev/context#WithValue withvalue不建议用内置类型，所以我的理解是context里一般不会有string定义的内容吧。

看起来用string能读到别的定义string key的value，另外感觉日志系统尽量不要侵入业务逻辑

**Comment by li-jin-gou** [comment]
PATL @rogerogers

**Comment by rogerogers** [comment]
> > https://pkg.go.dev/context#WithValue withvalue不建议用内置类型，所以我的理解是context里一般不会有string定义的内容吧。
> 
> 看起来用string能读到别的定义string key的value，另外感觉日志系统尽量不要侵入业务逻辑

做了一个兼容，不过官方建议应该作为一种共识，尽量避免在context中使用内置类型。
