### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by cold-runner** [hertz-contrib/logger#43]
在https://github.com/hertz-contrib/logger/tree/main/zap#readme 的 `Multiple zapcore Example`部分中，并没有使用`hlog.SetLogger(logger)`将新创建的zap logger实例注入到hlog包的FullLogger接口中，这导致了`hlog.Infof()`方法实际调用的是hlog包中默认的`defaultLogger`实例中的`Infof()`方法，而不是新创建的zap logger实例实现的`Infof()`方法

**Comment by FGYFFFF** [comment]
看起来应该是写示例的时候漏掉了，你方便提个 pr 修改下吗

**Comment by li-jin-gou** [comment]
cc @rogerogers

**Comment by cold-runner** [comment]
> 看起来应该是写示例的时候漏掉了，你方便提个 pr 修改下吗

好的
