### ISSUE TITLE
hertzlogrus打印日志不转译换行符

### ISSUE THREAD

**Issue by wheelergeo** [hertz-contrib/logger#48]
hlog.SetLogger(hertzlogrus.NewLogger())                                                                                                                                                           
hlog.SetLevel(conf.LogLevel()) 
怎么配置，才可以日志输出换行，而不是输出\n，不然panic调用栈挤成一块不方便定位

**Comment by rogerogers** [comment]
默认使用的jsonformatter，方便日志收集，你可以使用日志收集工具解析开 json 然后查看日志，
或者你可以通过自定义 logrus formatter 来实现
```go
package main

import (
	"github.com/cloudwego/hertz/pkg/common/hlog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	"github.com/sirupsen/logrus"
)

func main() {
	l := logrus.New()
	l.SetFormatter(&logrus.TextFormatter{})
	hertzlogrus.NewLogger(hertzlogrus.WithLogger(l))
	hlog.Info("hello\nworld")
}
```

**Comment by wheelergeo** [comment]
TextFormatter也是不输出换行，看来只能通过自定义 logrus formatter 来实现

**Comment by rogerogers** [comment]
TextFormatter会输出换行的，方便的话可以贴下代码

**Comment by rogerogers** [comment]
我刚发布了一个新版，你也可以更新下版本，再试下

**Comment by wheelergeo** [comment]
`                                                                                                                                                                                            
    l := logrus.New()                                                                                                                                                                                     
    l.SetFormatter(&logrus.TextFormatter{})                                                                                                                                                               
    hlog.SetLogger(hertzlogrus.NewLogger(hertzlogrus.WithLogger(l)))                                                                                                                                      
    hlog.SetLevel(conf.LogLevel())                                                                                                                                                                        
    if logger != nil {                                                                                                                                                                                    
        hlog.SetLogger(logger)                                                                                                                                                                            
    }                                                                                                                                                                                                     
    asyncWriter := &zapcore.BufferedWriteSyncer{                                                                                                                                                          
        WS: zapcore.AddSync(&lumberjack.Logger{                                                                                                                                                           
            Filename:   conf.GetConf().Hertz.LogFileName,                                                                                                                                                 
            MaxSize:    conf.GetConf().Hertz.LogMaxSize,                                                                                                                                                  
            MaxBackups: conf.GetConf().Hertz.LogMaxBackups,                                                                                                                                               
            MaxAge:     conf.GetConf().Hertz.LogMaxAge,                                                                                                                                                   
        }),                                                                                                                                                                                               
        FlushInterval: time.Minute,                                                                                                                                                                       
    }                                                                                                                                                                                                     
                                                                                                                                                                                                          
    hlog.SetOutput(io.MultiWriter(asyncWriter, os.Stdout))                                                                                                                                                
    h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {                                                                                                                                       
        asyncWriter.Sync()                                                                                                                                                                                
    })                                                                                                                                                                                                    
    hlog.Info("hello\nworld")`

**Comment by wheelergeo** [comment]
`func registerLogger(h *server.Hertz, logger hlog.FullLogger) {                                                                                                                                            
    // hlog                                                                                                                                                                                               
    l := logrus.New()                                                                                                                                                                                     
    l.SetFormatter(&logrus.TextFormatter{})                                                                                                                                                               
    hlog.SetLogger(hertzlogrus.NewLogger(hertzlogrus.WithLogger(l)))                                                                                                                                      
    hlog.SetLevel(conf.LogLevel())                                                                                                                                                                        
    if logger != nil {                                                                                                                                                                                    
        hlog.SetLogger(logger)                                                                                                                                                                            
    }                                                                                                                                                                                                     
    asyncWriter := &zapcore.BufferedWriteSyncer{                                                                                                                                                          
        WS: zapcore.AddSync(&lumberjack.Logger{                                                                                                                                                           
            Filename:   conf.GetConf().Hertz.LogFileName,                                                                                                                                                 
            MaxSize:    conf.GetConf().Hertz.LogMaxSize,                                                                                                                                                  
            MaxBackups: conf.GetConf().Hertz.LogMaxBackups,                                                                                                                                               
            MaxAge:     conf.GetConf().Hertz.LogMaxAge,                                                                                                                                                   
        }),                                                                                                                                                                                               
        FlushInterval: time.Minute,                                                                                                                                                                       
    }                                                                                                                                                                                                     
                                                                                                                                                                                                          
    hlog.SetOutput(io.MultiWriter(asyncWriter, os.Stdout))                                                                                                                                                
    h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {                                                                                                                                       
        asyncWriter.Sync()                                                                                                                                                                                
    })                                                                                                                                                                                                    
    hlog.Info("hello\nworld")                                                                                                                                                                             
}     `

**Comment by wheelergeo** [comment]
```
func registerLogger(h *server.Hertz, logger hlog.FullLogger) {                                                                                                                                            
    // hlog                                                                                                                                                                                               
    l := logrus.New()                                                                                                                                                                                     
    l.SetFormatter(&logrus.TextFormatter{})                                                                                                                                                               
    hlog.SetLogger(hertzlogrus.NewLogger(hertzlogrus.WithLogger(l)))                                                                                                                                      
    hlog.SetLevel(conf.LogLevel())                                                                                                                                                                        
    if logger != nil {                                                                                                                                                                                    
        hlog.SetLogger(logger)                                                                                                                                                                            
    }                                                                                                                                                                                                     
    asyncWriter := &zapcore.BufferedWriteSyncer{                                                                                                                                                          
        WS: zapcore.AddSync(&lumberjack.Logger{                                                                                                                                                           
            Filename:   conf.GetConf().Hertz.LogFileName,                                                                                                                                                 
            MaxSize:    conf.GetConf().Hertz.LogMaxSize,                                                                                                                                                  
            MaxBackups: conf.GetConf().Hertz.LogMaxBackups,                                                                                                                                               
            MaxAge:     conf.GetConf().Hertz.LogMaxAge,                                                                                                                                                   
        }),                                                                                                                                                                                               
        FlushInterval: time.Minute,                                                                                                                                                                       
    }                                                                                                                                                                                                     
                                                                                                                                                                                                          
    hlog.SetOutput(io.MultiWriter(asyncWriter, os.Stdout))                                                                                                                                                
    h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {                                                                                                                                       
        asyncWriter.Sync()                                                                                                                                                                                
    })                                                                                                                                                                                                    
    hlog.Info("hello\nworld")                                                                                                                                                                             
}                                                                                                                                                                                                         
```

**Comment by li-jin-gou** [comment]
hlog.SetOutput(io.MultiWriter(asyncWriter, os.Stdout))  os.Stdout 性能垃圾建议真实运行不要打开

**Comment by wheelergeo** [comment]
> hlog.SetOutput(io.MultiWriter(asyncWriter, os.Stdout)) os.Stdout 打印性能垃圾，建议真实运行时不要打开

开发环境用

**Comment by wheelergeo** [comment]
github.com/hertz-contrib/obs-opentelemetry/logging/logrus v0.1.1

**Comment by li-jin-gou** [comment]
![image](https://github.com/hertz-contrib/logger/assets/97824201/0c598549-baa0-423e-a626-e69935cd71bd)

你看初始化的 l 设置了 TextFormatter 但是并没有传给 hlog  @wheelergeo

**Comment by li-jin-gou** [comment]
看到了，传了。还得 @rogerogers  看下了

**Comment by wheelergeo** [comment]
> ![image](https://private-user-images.githubusercontent.com/97824201/295484593-0c598549-baa0-423e-a626-e69935cd71bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzIxNDYsIm5iZiI6MTcwNDg3MTg0NiwicGF0aCI6Ii85NzgyNDIwMS8yOTU0ODQ1OTMtMGM1OTg1NDktYmFhMC00MjNlLWE2MjYtZTY5OTM1Y2Q3MWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA3MzA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNGIwMzBlYWIwMmVhNWViYjE5ODBlMGNlNWE3MDRkYWJjZGJlOGIyYWI3ZjU0NWI3MDE0NzUwNTJiMjQyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nRaxNGFDsXY9YY2moNcMFytJdSEdLU4V-CmKGZKPJSk)
> 
> 你看初始化的 l 设置了 TextFormatter 但是并没有传给 hlog @wheelergeo

他的代码没传。我的传了

**Comment by rogerogers** [comment]
更新下版本吧，有个修复之前没发版。

**Comment by wheelergeo** [comment]
> 更新下版本吧，有个修复之前没发版。
刚忘了贴了，我之前使用的是 “github.com/hertz-contrib/obs-opentelemetry/logging/logrus” v0.1.1的hertzlogrus.NewLogger
现在替换成你刚发布的"github.com/hertz-contrib/logger/logrus" v1.0.1，还是一样，不输出换行

**Comment by rogerogers** [comment]
`SetOutput` 直接用 `os.Stdout` 可以，asyncWriter 做了优化应该，我看下。

**Comment by wheelergeo** [comment]
如果SetOutput 直接用 os.Stdout确实能输出换行，但是输出的不是logrus默认TextFormat，是一个比较奇怪的格式
```
INFO[0000] hello
world
INFO[0000] HERTZ: Using network library=netpoll
```

**Comment by rogerogers** [comment]
> 如果SetOutput 直接用 os.Stdout确实能输出换行，但是输出的不是logrus默认TextFormat，是一个比较奇怪的格式
> 
> ```
> INFO[0000] hello
> world
> INFO[0000] HERTZ: Using network library=netpoll
> ```

这个 0000 是 logrus 时间的位置，可以使用 logrus.TextFormatter{FullTimestamp: true}

**Comment by wheelergeo** [comment]
这个设置stdout为输出，格式不是logrus默认的格式，和单独只设置asyncWriter输出的格式不一样。而且设置MultiWriter同时输出标准输出和文件不转移换行符的问题还没解决。单独设置asyncWriter为输出换行符也不转义

**Comment by rogerogers** [comment]
> 这个设置stdout为输出，格式不是logrus默认的格式

这个设置stdout为输出，格式不是logrus默认的格式，这个是一致的吧。

asyncWriter 主要是为了生产环境性能考虑，测试环境可以直接输出到 `stdout` 或文件，输出不换行看上去是 logrus 本身的一个问题，如果比较在意这些 可以考虑切换 zap，

```go
package main

import (
	"context"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"io"
	"os"
	"runtime/debug"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	hertzzap "github.com/hertz-contrib/logger/zap"
)

func main() {
	h := server.New()
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS:            os.Stdout,
		FlushInterval: time.Second,
	}
	hlog.SetLogger(hertzzap.NewLogger(hertzzap.WithCoreEnc(zapcore.NewConsoleEncoder(zap.NewDevelopmentEncoderConfig()))))
	hlog.SetOutput(io.MultiWriter(asyncWriter, os.Stdout))
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		defer func() {
			if recover() != nil {
				hlog.Infof("%s", debug.Stack())
			}
		}()
		ctx.Data(consts.StatusOK, consts.MIMETextPlain, []byte("hello world"))
		panic("hello")
	})
	h.Spin()
}
```

**Comment by rogerogers** [comment]
可以考虑搭建一个 loki 系统，https://juejin.cn/post/7324011337264021514 ，超级方便 👀
