### ISSUE TITLE
Bring your own slog handler

### ISSUE THREAD

**Issue by kamikazechaser** [hertz-contrib/logger#52]
**Is your feature request related to a problem? Please describe.**

Feature request.

The slog implementation defaults to the [JSON handler](https://github.com/hertz-contrib/logger/blob/main/slog/logger.go#L89). Slog can be adapted to use pretty much every format/opinion out there and it should therefore be flexible.

**Describe the solution you'd like**

Expose `Logger.L` to override `*slog.Logger` directly or pass a functional option to inject a custom `slog.Handler`.

**Describe alternatives you've considered**

Implement the entire `hlog.FullLogger` interface.

**Additional context**

N/A

**Comment by rogerogers** [comment]
slog does not provide a way to modify the output. If modification is allowed, then `SetOutPut` will have problems

**Comment by kamikazechaser** [comment]
I see that now. Slog itself doesn't allow you to update the io.Writer so this feat will be impossible (atleast with slog). Thanks.
