### ISSUE TITLE
the latency value in access log is too long!!!

### ISSUE THREAD

**Issue by teresadq** [hertz-contrib/logger#58]
**Describe the bug**

When using access log middleware and setup `${latency}`, the output value contains too many white space!!!

**To Reproduce**
use the code below:
```
	h.Use(
		accesslog.New(
			accesslog.WithFormat(`[${time}] status=${status} latency="${latency}" method=${method} path=${path} queryParams=${queryParams}`),
		),
	)
```

**Expected behavior**

we expect the output is `latency="459ns"`. But we got `latency="        459ns"`.

**Screenshots**

![image](https://github.com/user-attachments/assets/276f10b4-0e11-4de9-83a6-e8bb9bb0c267)

**Hertz version:**

hertz: v0.9.3

**Environment:**

go version go1.23.1 linux/amd64

**Comment by StellarisW** [comment]
hello, that's because the accesslog will right-align `${latency}` part:

https://github.com/hertz-contrib/logger/blob/e4ce8c54dd97f0b39301b62c5334fef2a7aad7a2/accesslog/tags.go#L167

cc @Skyenought, is it ok to change `%13v` to `%v` ?

**Comment by teresadq** [comment]
@StellarisW I also raised a `feature request`: https://github.com/hertz-contrib/logger/issues/59

**Comment by rogerogers** [comment]
```go
accesslog.Tags[accesslog.TagLatency] = func(output accesslog.Buffer, c *app.RequestContext, data *accesslog.Data, extraParam string) (int, error) {
    latency := data.Stop.Sub(data.Start)
    return output.WriteString(fmt.Sprintf("%v", latency))
}
h.Use(
    accesslog.New(
        accesslog.WithFormat(`[${time}] status=${status} latency="${latency}" method=${method} path=${path} queryParams=${queryParams}`),
    ),
)
```
These several spaces are for adjusting the output style of the console. They can be adjusted through the custom output method.

**Comment by rogerogers** [comment]
Closing based on the comment above. Feel free to reopen if the problem still exists. Thank you
