### ISSUE TITLE
support skip paths in access log middleware

### ISSUE THREAD

**Issue by teresadq** [hertz-contrib/logger#59]
I want to disable the access log for the `/healthz` path in k8s pod.
But I didn't found the interface for this functionality.

Should we add some options for this, which is implemented in `Gin` framwork, as below
```
	r.Use(gin.LoggerWithConfig(gin.LoggerConfig{
		SkipPaths: []string{"/ping_1"},
	}))
```

**Comment by StellarisW** [comment]
@teresadq You can add such an option in `accesslog`, PR is welcomed!

**Comment by teresadq** [comment]
> @teresadq You can add such an option in `accesslog`, PR is welcomed!

resolved, use `WithLogConditionFunc` option.

```
		accesslog.New(
			accesslog.WithFormat(`[${time}] status=${status} latency="${latency}" method=${method} path=${path} body=${body}`),
			accesslog.WithLogConditionFunc(func(ctx context.Context, c *app.RequestContext) bool {
				if c.FullPath() == "/healthz" {
					return false
				}
				return true
			}),
		),
```
